name: macetohuerto
description: "MVP controlador de macetohuerto (sin MQTT)"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.3
  intl: 0.20.2
  uuid: ^4.5.1
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  flutter_native_timezone:
    path: packages/flutter_native_timezone
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true

